### ISSUE TITLE
UI tidy

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#1143]
- [x] Fix CSS for Logic dropdown
- [x] Add tooltips (at least for Misc.) for the Item Rando Options
- [x] Indicate that Shuffling Shops for Item Rando forces Cross Kong purchases to be on
- [x] Fix CSS for Medals Section and Move it over to Global Settings
- [x] Add Logic to Door 1/2 Req. for what can be the Counts
- [x] Use a Cog icon instead of Customize button and get rid of disable logic
- [x] Replace all instances of "Random Selection" with a Dice Icon
- [x] Fix CSS Padding on Color Selectors
- [x] Move all line break tags outside of Flex Containers
- [x] Fix Colors for "More Info" button on homepage
- [x] Change to "Enable Shop Hints"
- [x] Make seed generation section make better use of empty space
- [x] Secret :)
- [x] Fix Double Click Generation

**Comment by Cfox7** [comment]
- Fix CSS for Logic dropdown
- Add tooltips (at least for Misc.) for the Item Rando Options
- Indicate that Shuffling Shops for Item Rando forces Cross Kong purchases to be on
- Fix CSS for Medals Section and Move it over to Global Settings
- Add Logic to Door 1/2 Req. for what can be the Counts
- Use a Cog icon instead of Customize button and get rid of disable logic
- Replace all instances of "Random Selection" with a Dice Icon
- Fix CSS Padding on Color Selectors
- Move all <hr> tags outside of Flex Containers
- Fix Colors for "More Info" button on homepage
- Change to "Enable Shop Hints"
- Make seed generation section make better use of empty space
- Secret :)
