### ISSUE TITLE
Plandomizer support?

### ISSUE THREAD

**Issue by TheSoundDefense** [2dos/DK64-Randomizer#1227]
I would be interested in implementing this myself if nobody is currently working on it, but I was wondering if there were any blocking bugs, or any other preliminary work that would prevent a plandomizer from being implemented.

**Comment by pbeierle22** [comment]
I foresee issues in trying to place more items than we have flags for (e.g. placing more than 40 medals), so maybe the front end has some restrictions? Could be that the first version of this is very tedious to use by placing every single item but more work could go into having "flex" slots that could sort things out. I expect this would probably be a separate flow for plando seeds to just be beatable instead of 101%. 

This would be an **enormous** undertaking in the UI alone. If you get that far I can assist with massaging the logic.

**Comment by TheSoundDefense** [comment]
Thanks for responding. I will work on a UI and submit a PR if I have something that works well.
