### ISSUE TITLE
EEPROM error (cannot save)

### ISSUE THREAD

**Issue by 03bgood** [2dos/DK64-Randomizer#1229]
I'm using RetroArch (Mupen64Plus-Next) and I get an error message about bad EEPROM and not being able to save data. Haven't found anyone else with this issue. What's going on?

Update: Just read it doesn't support RetroArch or Mupen64Plus and it says there are graphical glitches but I'm using the ParaLLEl plugin and so far, there aren't any. Will this ever be fixed to include RA and M64P? I can't use Bizhawk or Project64 because I'm running this off a Steam Deck and that doesn't support either emulator.

**Comment by theballaam96** [comment]
In addition to 2dos's last paragraph:
The EEPROM message, whilst it can only indicate about save issues, does in general indicate that an emulator hasn't been correctly set up. As such, certain elements of the game _may_ not run correctly, including vintage DK64 emulation bugs like grabbing trees/vines/poles/ledges warping you out of the level or exerting strange behaviour.

If you do continue with RetroArch on the steam deck, savestates will bypass the save issues, but you _may_ experience other issues that we cannot resolve purely because it's an emulation problem rather than a Randomizer problem

**Comment by Killklli** [comment]
Closing for now as we've done as much as we can for most other emulators its just waiting for them to catch up as they go.
