### ISSUE TITLE
Creepy Castle Crash in 2.0 Dev Branch

### ISSUE THREAD

**Issue by ll-Spade-ll** [2dos/DK64-Randomizer#1391]
I was in Creepy Castle and I noticed the level was only loading half of the way up the castle. After awhile of standing there confused the game crashed and this is the crash.

![seed684221](https://user-images.githubusercontent.com/130863644/232247925-6709dbda-2e29-4b9d-be72-5b41f97f709d.PNG)

**Comment by theballaam96** [comment]
Mornin,
This seems to be an interesting crash of the game being unable to allocate the necessary space to draw the moon. It's especially weird that you say that Castle wasn't loading for you at all.
To fully diagnose this issue, we're going to need a few things from you:
- The spoiler log (Should be a `.json` file)
- A dkp to your ROM (Use this tool: https://dev.dk64randomizer.com/dkp_maker)
- Could you confirm the emulator you're using. It looks like this is BizHawk, but just want to ensure that you are using the special DK64 fork of BizHawk
- Were you doing anything unusual beforehand that you think might be worthwhile us knowing in order to assist us with replicating this?

**Comment by ll-Spade-ll** [comment]
Where do you want me to send the spoiler log and dkp. I'm unable to send them on here unless I can convert them to another file type. Also, the emulator is BizHawk for dk64.

**Comment by theballaam96** [comment]
You can either join the discord at http://discord.dk64randomizer.com and post both in the #dev-bug-reports channel or post something like a Google drive link in here

**Comment by ll-Spade-ll** [comment]
Thanks. Here it is.
ahttps://drive.google.com/drive/folders/1MfRRKrh8RjsH02DCuhRNMpyBwufNB0MX?usp=sharing

**Comment by theballaam96** [comment]
> Thanks. Here it is.
> ahttps://drive.google.com/drive/folders/1MfRRKrh8RjsH02DCuhRNMpyBwufNB0MX?usp=sharing

Could you change the visibility to "anyone with the link can view"

**Comment by ll-Spade-ll** [comment]
Sorry, I changed it now.

**Comment by theballaam96** [comment]
Thank you. We will take a look into it over the coming days

**Comment by theballaam96** [comment]
Might be resolved by #1401 . Will wait for ~2 weeks for future bug reports either in git issues or in the 2.0 bug reports discord channel before making a decision on whether to close this
