### ISSUE TITLE
Switchsanity

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#1650]
## OVERALL DONE
- [x] Base Hack
- [x] Writer
- [x] Primary Logic
- [x] Custom Location Logic
- [x] Spoiler
- [x] Microhints
- [x] Remove top monkeyport
- [x] UI

## SUBTRACKER
**Isles**
- [x] Isles Monkeyport: Blast, Balloon or Port (spring?)
- [x] Helm Lobby Gone: Instrument or Gone (Decided against balloon because of bonus)
- [x] Aztec Lobby Door
- [x] Fungi Lobby Fairy Door
- [x] Isles Trombone Pad (To spawn the rocketbarrel)

**Japes**
- [x] Japes Feather Gate
- [x] Japes Rambi Gate
- [x] Japes Painting Gate
- [x] Japes Tunnel Alcove

**Aztec**
- [x] Aztec Blueprint Door
- [x] Aztec Llama Temple Switches
- [x] Aztec Llama Snoop Switch
- [x] Aztec Guitar Pad (Back of Aztec access)

**Galleon**
- [x] Galleon Lighthouse Gate
- [x] Galleon Ship-side gates
- [x] Galleon Cannon Game Gate

**Fungi**
- [x] Fungi Yellow Tunnel Switch
- [x] Fungi Green Tunnel Switches

**Comment by AlmostSeagull** [comment]
Going to suggest: 
Castle: Ballroom switch 
Isles: Helm Lobby Kasplat bridge switch (if it persists through tagging)

**Comment by theballaam96** [comment]
> Isles: Helm Lobby Kasplat bridge switch (if it persists through tagging)

Lrauq — Today at 11:23 AM
i think keeping this to level-unlocking things is best
keep the GBs purer
like im not sold on vases/stone bridge switch shuffle

**Comment by 2dos** [comment]
Suggesting removing Helm Pineapple switch from this. This is because getting to and activating the main room in the blastomatic requires one move from each kong (Orangstand -> Pineapple -> Mini Monkey -> Gorilla Grab -> Rocketbarrel). Randomizing just that switch would ruin the intended one move per kong sequence.

Alternatively, expand the opening helm sequence by randomizing all of the items I mentioned (would take a lot of re-working of the obstacles), but that would be outside Switchsanity.
