### ISSUE TITLE
Colorblind Mode

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#460]
- [x] Make code to generate and push colorized textures to ROM
- [x] Fix crashing issues
- [x] UI

### Expansion
- [x] Shockwave
- [x] Klaptraps
- [x] Wrinkly
- [x] Slam Switches
- [x] Blueprints
- [x] Bells
- [x] Rotating Room Tiles
- [x] Helm Lasers
- [x] Potions
- [x] Mushrooms

### Shockwave Textures (32x32 RGBA32 textures)
- Green: 0x133D -> 0x1342
- Blue: 0x1268 -> 0x126D
- Purple: 0x1356 -> 0x135B
- Red: 0x1327 -> 0x132C
- Yellow: 0x1321 -> 0x1326

### Bells (Table 4, Files 692 and 693)
- Color 1: #A8FF79 (Change this as you wish)
- Color 2: #00FF00 (Change this as you wish)
- Color 1 Writes: 0x214, 0x244, 0x264, 0x274, 0x284
- Color 2 Writes: 0x224, 0x234, 0x254

### 3D Blueprints (Table 4)
- Alter RGBA into models 0xDD->0xE1 (Order: Tiny, DK, Chunky, Diddy, Lanky).
- Each RGBA has a different color indicated in brackets.
- Offsets into file:
- Group 1: 0x52C, 0x54c, 0x57C, 0x58C, 0x5AC, 0x5CC, 0x5FC, 0x61C
- Group 2: 0x53C, 0x55C, 0x5EC, 0x60C
- Group 3: 0x56C, 0x59C, 0x5BC, 0x5DC

Example colors with Tiny's Blueprint:
Color 1: #D200D2
Color 2: #A400A4
Color 3: #FF79E9

All are roughly similar, so you may want to ignore the color groups for colorblind mode

### Klaptraps (Table 25)
Green: 0xF35, 0xF37, 0xF39, 0xF31 -> 0xF33
Purple: 0xF3C -> 0xF41
Red: 0xF44 -> 0xF49

### Lasers (Table 7)
Yellow: 0x310 -> 0x31B	
Red: 0x2EC -> 0x2F7
Blue: 0x16B -> 0x176
Purple: 0x2F8 -> 0x303
Green: 0x304 -> 0x30F 

### Potions
ACTOR
Group 1 (#1FDF5F)
0x34

Group 2 (#0A471E)
0x44
0x54
0xA4

Group 3 (#79EB79)
0x64
0x74
0x84
0xE4

Group 4 (#8CD8B2)
0x94

Group 5 (#169F44)
0xB4
0xC4
0xD4

Group 6 (Bottle Neck)
0xF4
0x104
0x114
0x124
0x134
0x144
0x154
0x164

MODEL TWO

Group 1 (#1FDF5F)
0x144

Group 2 (#0A471E)
0x154
0x164
0x1B4

Group 3 (#79EB79)
0x174
0x184
0x194
0x1F4

Group 4 (#8CD8B2)
0x1A4

Group 5 (#169F44)
0x1C4
0x1D4
0x1E4

Group 6 (Bottle Neck)
0x204
0x214
0x224
0x234
0x244
0x254
0x264
0x274

Files (Order: DK, Diddy, Lanky, Tiny, Chunky, Any)
Actors (Big): 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF2
Actors (Small): 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA
Model Two: 91, 498, 89, 499, 501, 502

**Comment by theballaam96** [comment]
Color Palette Ideas:

https://davidmathlogic.com/colorblind/

Protanopia/ Deuteranopia:
- DK: Orange (#E69F00)
- Diddy:  Brown (#73403A)
- Lanky: Dark Blue (#0072B2)
- Tiny: Black (#000000)
- Chunky: White (#FFFFFF)

Tritanopia:
- DK: Black (#000000)
- Diddy: Red (#FF0000)
- Lanky: Light Blue (#00E7FF)
- Tiny: Murky Purple (#884556)
- Chunky: White (#FFFFFF)

Get rid of "white hair" kasplats in main maps

**Comment by theballaam96** [comment]
https://docs.google.com/spreadsheets/d/1utd1C6hWMFlfzzQewPySrpDkZor2ApDkiaZuLEB7kHs/edit?usp=sharing

**Comment by AlmostSeagull** [comment]
Another color palette idea, using the same site: 

Protanopia/ Deuteranopia:

- DK: Orange (yellow, orange) #FFB000
- Diddy: Pink (grey, brown) #FF6666
- Lanky: Blue (blue-ish, blue) #00A3FF
- Tiny: Lime (sandy, some pinkish white) #E1F90C
- Chunky: Dark red (dark grey, dark grey) #4C2E2A

![image](https://user-images.githubusercontent.com/107404587/192595130-9875e822-d0cc-4c8f-93d6-5f53fffdc8d4.png)

Tritanopia:

- DK: Blue (green) #1D439E
- Diddy: Red (red) #FF0000
- Lanky:  Light blue (light blue) #66C7FF
- Tiny: Yellow (pink) #FFC302
- Chunky: Black (black) #000000

![image](https://user-images.githubusercontent.com/107404587/192595841-6a1da0e8-3825-4849-84d4-c475fae8e231.png)

And white kasplats can still be white, is the intention.

**Comment by theballaam96** [comment]
![image](https://user-images.githubusercontent.com/18194547/192625297-4c294952-603a-498f-a842-bbf6fd758138.png)
![image](https://user-images.githubusercontent.com/18194547/192625316-363652d1-f195-4119-9948-b72d60b22226.png)
![image](https://user-images.githubusercontent.com/18194547/192625335-0d9e3475-c1ef-448d-b036-c2eb9b5dded8.png)
Color masking seems to be functioning

**Comment by AlmostSeagull** [comment]
Cool! Good work!

**Comment by AlmostSeagull** [comment]
Feedback I collected on this: 
Red-green: 
DK and TIny's color look similar to non-colorblind folks (looking at it now, it looks okay for Tritanopia for some reason :p)
Some colors look off
Blue-yellow: 
Lanky and Tiny's color look similar 
Tiny's color is a bit dark
Chunky's black color is objectively horrible 
Lanky's and Diddy's color lacks shading or something, looking into it
Suggestions: 
also colorblind kasplat shockwave color, klaptrap colors, beaver colors, wrinkly door colors, simian slam switches (and slam shockwave?)

I'll see what I can do to pick new colors and improve the shading/whatever makes diddy's color for example look bad.

**Comment by AlmostSeagull** [comment]
Btw I forget. Not sure if this is feedback I received but ehm... blueprint colors :P

**Comment by AlmostSeagull** [comment]
Okay, so I haven't been doing any work on this for a good (bad) while. I've been procrastinating since I found out that colored banana's are 8 images and patterning would be tough and my graphical skills would be lacking, not to mention visibility issues. 

I've had a bit of a brainwave and thought I'd write up my thoughts so far: 
I have found 3 working colors for each type of colorblindness. 1 color for Deuteranopia, however is very close to white, so I am considering texturing white kasplat hair, or making white kasplat hair black in that mode. (kasplat hair is allowed to be black, but CB's and such: NO way)

Now for the main obstacle: I have 3 colors and I need 5.  
![image](https://user-images.githubusercontent.com/107404587/203434271-e28a8bb8-7a24-4b3a-90bd-25bc53ac6596.png)
First plan was to texture the collectables for the 2 remaining colors. Color scheme wise a fair idea, actually texturing CB's and coins? Not easy

Second plan could be to add a glow to the spinning collectables 
Third plan could be a gradient, horizontally (because vertically is a fair bit harder) 
Fourth plan could be to add sparkles to 2 colors, like the ones on GB or on Crystal Caves's walls.

**Comment by AlmostSeagull** [comment]
Also, Krusha's belt and bracers color, the one we use to show which kong Krusha replaces... are also a thing to consider. This might be a blessing in disguise. Black and White are back in my mind as viable alternatives, but it does require some art work on the black collectables.

**Comment by theballaam96** [comment]
> Also, Krusha's belt and bracers color, the one we use to show which kong Krusha replaces... are also a thing to consider. This might be a blessing in disguise. Black and White are back in my mind as viable alternatives, but it does require some art work on the black collectables. 

Belt colors for Krusha are stored [here](  
https://github.com/2dos/DK64-Randomizer/blob/dev/randomizer/Patching/CosmeticColors.py#L175) and use a block coloring. If patterns are used as opposed to block colors, you'd have to have some code to generate the belt texture with your pattern

**Comment by AlmostSeagull** [comment]
Good to know! 
Alright I think I have a plan: 
1. DK will be the first color out of 3, for each respective category (pink will be yellow later, possibly. It looks the same to the target group)
2. Diddy will be the second color (purely because in 1 category it is red)
3. Tiny will be white
4. Lanky will be color 3. This is tricky as it needs a touch of patterning for prot. and deut. as it's too close to white. 
5. Chunky will be black with white outlines and/or a shiny effect on collectibles (means some work to be done) 
White kasplat hair will be patterned in colorblind mode, to make it clear that he is white. Only hurdle there is Lanky *also* being close to white. Close-to-white kasplats are a no-go. 

For cosmetics like Krusha's belt and kasplat hair the color Black isn't all too bad.

**Comment by AlmostSeagull** [comment]
All this talk about sniper scope... Might want to change the sniper crosshair from yellow to a different color in colorblind mode. Probably blue. Red/Blue seems to be discernable to everyone. Changing the green color seems lower priority to me. 
Actually, changing yellow to purple looks like it would work. 
Also, this change seems not needed for tritanopia mode, so just prot/deut.

**Comment by AlmostSeagull** [comment]
Also, I took a look at blue/yellow on the beavers, but it looks fine on all colorblind modes, so I'm kind of thinking there's absolutely no need to do Beaver recoloring.

**Comment by AlmostSeagull** [comment]
Blueprint model2 is done, but keeping Blueprints unchecked until the blueprint overview at Snides has been done, or has been confirmed to be too difficult to be feasible

**Comment by AlmostSeagull** [comment]
Possible additional idea: Lanky's piano game. I have found the textures required, I believe. Probably not quite easy, though.
