### ISSUE TITLE
db is undefined error - Firefox Incognito

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#959]

**Comment by AlmostSeagull** [comment]
Just checked this one. I probably misremember. I thought it was upon exporting settings string, but it's currently upon inputting a rom, preventing the green checkmark from appearing. (does also prevent seed gen, because the site will mark the rom as bad when trying to generate a seed). 

Import/Export settings string works in Frefox Incognito. Sorry if it's just me misremembering, though.

**Comment by AlmostSeagull** [comment]
https://discord.com/channels/463917049782075395/559837167430664203/1112856215853207632
